config/routes.rb
Bugtracker::Application.routes.draw do
  devise_for :users

  resources :products do
    resources :bugs
  end

  root :to => "products#index"

end

app/models/bug.rb
class Bug < ActiveRecord::Base
  belongs_to :product
  belongs_to :user
  attr_accessible :description, :priority, :reporter, :status, :title
  validates :title, :description, :priority, :status, :presence => true
  validates :description, :presence => true, :length => { :minimum => 6 }
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :description, :title

  validates :title, :presence => true

  has_many :bugs, :dependent => :delete_all
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  before_filter :find_product
  before_filter :find_bug, :only => [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, :except => [:index, :show]

  def new
    @bug = @product.bugs.build
  end

  def create
    @bug = @product.bugs.build(params[:bug])
    @bug.user = current_user
    if @bug.save
      flash[:notice] = "Bug has been created."
      redirect_to [@product, @bug]
    else
      flash[:alert] = "Bug has not been created."
      render :action => "new"
    end
  end

  def show
  end

  def edit
  end

  def update
    if @bug.update_attributes(params[:bug])
      flash[:notice] = "Bug has been updated."
      redirect_to [@product, @bug]
    else
      flash[:alert] = "Bug has not been updated."
      render :action => "edit"
    end
  end

  def destroy
    @bug.destroy
    flash[:notice] = "Bug has been deleted."
    redirect_to @product
  end

  private
    def find_product
      @product = Product.find(params[:product_id])
    end

    def find_bug
      @bug = @product.bugs.find(params[:id])
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :find_product, :only => [:show, :edit, :update, :destroy]

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(params[:product])
    if @product.save
      flash[:notice] = "Game product has been created."
      redirect_to @product
    else
      flash[:alert] = "Product has not been created."
      render :action => "new"
    end
  end

  def show
  end

  def edit
  end

  def update
    if @product.update_attributes(params[:product])
      flash[:notice] = "Game product has been updated."
      redirect_to @product
    else
      flash[:alert] = "Game product has not been updated."
      render :action => "edit"
    end
  end

  def destroy
    @product.destroy
    flash[:notice] = "Game product has been deleted."
    redirect_to products_path
  end

  private
    def find_product
      @product = Product.find(params[:id])
      rescue ActiveRecord::RecordNotFound
      flash[:alert] = "The game product you were looking for could not be found."
      redirect_to products_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bugs_helper.rb
module BugsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/bugs/_form.html.erb
<%= form_for [@product, @bug] do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :priority %><br>
    <%= f.select(:priority, [['High', "High"], ['Medium', "Medium"], ['Low', "Low"], ['Trivial', "Trivial"]]) %>
  </p>
  <p>
    <%= f.label :status %><br>
    <%= f.select(:status, [['Open', "Open"], ['Closed', "Closed"], ['Verified', "Verified"]]) %>
  </p>
  <p>
    <%= f.label :reporter %><br>
    <%= f.text_field :reporter %>
  </p>
  <%= f.submit :class => 'btn btn-primary'%>
<% end %>

app/views/bugs/edit.html.erb
<h2>Editing a bug in <%= @product.title %></h2>
<%= render "form" %>

app/views/bugs/new.html.erb
<h2>New Bug</h2>
<%= render "form" %>

app/views/bugs/show.html.erb
<div id='bug'>
  <h2>Bug Title: <%= @bug.title %></h2>
  <span id='author'>Bug filed by <%= @bug.user.email %></span>
  <p><b>Bug Description:</b> <%= simple_format(@bug.description) %></p>
  <p><b>Priority:</b> <%= @bug.priority %></p>
  <p><b>Status:</b> <%= @bug.status %></p>
  <p><b>Reporter:</b> <%= @bug.reporter %></p>
  <%= link_to "Edit Bug", [:edit, @product, @bug] %><br>
  <%= link_to "Delete Bug", [@product, @bug], :method => :delete,
       :confirm => "Are you sure you want to delete this bug?" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Bug Tracker" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Bug Tracker</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "CodeFellows", "https://www.codefellows.org/"  %></li>
              <li><%= link_to "CF WOC July 2013", "https://canvas.instructure.com/courses/801977"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
              <nav>
                <div class="row1">
                <% if user_signed_in? %>
                  Signed in as <%= current_user.email %>
                  <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
                <% else %>
                  <%= link_to "Sign up", new_user_registration_path %>
                <% end %>
                </div>
                <%= link_to "Sign in", new_user_session_path %>
              </nav>
            <%= yield %>
          </div>
          <div class="span3">
            <div class="well sidebar-nav">
              <ul class="nav nav-list">
                <li class="nav-header">About This App</li>
                This is a bug tracking system for any game products to keep track of the current bugs filed. Users must sign in in order to create a new product and/or to create a bug report for a particular game product.
              </ul>
            </div><!--/.well -->
          </div><!--/span-->
        </div><!--/row-->

      <footer>
        <p></p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>

<%= f.error_messages %>

  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  <%= f.submit :class => 'btn btn-primary' %>
<% end %>

app/views/products/edit.html.erb
<h2>Edit game product</h2>
<%= render "form" %>

app/views/products/index.html.erb
<%= link_to "New Game Product", new_product_path %>

<h2>Game Products</h2>
<ul>
  <% @products.each do |product| %>
    <li><%= link_to product.title, product %></li>
  <% end %>
</ul>

app/views/products/new.html.erb
<h2>New Game Product</h2>
<%= render "form" %>

app/views/products/show.html.erb
<h2><%= @product.title %></h2>

<p><%= link_to "Edit Game Product", edit_product_path(@product) %></p>
<p><%= link_to "Delete Game Product",
     product_path(@product),
     :method => :delete,
     :confirm => "Are you sure you want to delete this game product?" %></p>
<p><b><%= link_to "New Bug", new_product_bug_path(@product) %></b></p>

<ul class="nav nav-list" id='bugs'>
  <% @product.bugs.each do |bug| %>
    <li class="nav-header">
      Bug <%= bug.id %><%= link_to bug.title, [@product, bug] %>
    </li>
  <% end %>
</ul>